# Generated by Django 5.0.14 on 2026-07-20 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('badge', models.CharField(blank=True, max_length=50, null=True)),
                ('badge_class', models.CharField(blank=True, default='badge-w', max_length=50, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('specs', models.JSONField(blank=True, default=list, help_text='List of specifications, e.g. ["900ml", "36hr cold"]')),
                ('color', models.CharField(help_text='Hex color code, e.g. #ff0000', max_length=7)),
                ('svg', models.TextField(blank=True, help_text='Inline SVG code representing the bottle design', null=True)),
                ('image', models.ImageField(blank=True, help_text='Main photo of the product', null=True, upload_to='products/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
        ),
    ]
